
/**
Constructor
Do not call Function in Constructor.
*/
class DirectSample()
{
	super();

	//TODO:edit here

}
extends AView;


function DirectSample*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function DirectSample*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function DirectSample*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
