
/**
Constructor
Do not call Function in Constructor.
*/
class OriginalView()
{
	super();

	//TODO:edit here

}
extends AView;


function OriginalView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function OriginalView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function OriginalView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
