
/**
Constructor
Do not call Function in Constructor.
*/
class StyleSample()
{
	super();

	//TODO:edit here

}
extends AView;


function StyleSample*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function StyleSample*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function StyleSample*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
