
/**
Constructor
Do not call Function in Constructor.
*/
class TemplateSample()
{
	super();

	//TODO:edit here

}
extends AView;


function TemplateSample*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function TemplateSample*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function TemplateSample*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
