
/**
Constructor
Do not call Function in Constructor.
*/
class WorkView()
{
	super();

	//TODO:edit here

}
extends AView;


function WorkView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function WorkView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function WorkView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
