
/**
Constructor
Do not call Function in Constructor.
*/
class FlexLayoutView2()
{
	super();

	//TODO:edit here

}
extends AView;


function FlexLayoutView2*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function FlexLayoutView2*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function FlexLayoutView2*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
