
/**
Constructor
Do not call Function in Constructor.
*/
class FlexLayoutView3()
{
	super();

	//TODO:edit here

}
extends AView;


function FlexLayoutView3*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function FlexLayoutView3*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function FlexLayoutView3*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
