
/**
Constructor
Do not call Function in Constructor.
*/
class SubView1()
{
	super();

	//TODO:edit here

}
extends AView;


function SubView1*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function SubView1*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function SubView1*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
