
/**
Constructor
Do not call Function in Constructor.
*/
class SubView2()
{
	super();

	//TODO:edit here

}
extends AView;


function SubView2*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function SubView2*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function SubView2*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
