
/**
Constructor
Do not call Function in Constructor.
*/
class ItemView2()
{
	super();

	//TODO:edit here

}
extends AView;


function ItemView2*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function ItemView2*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function ItemView2*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
