
/**
Constructor
Do not call Function in Constructor.
*/
class ItemView1()
{
	super();

	//TODO:edit here

}
extends AView;


function ItemView1*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function ItemView1*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function ItemView1*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
