
/**
Constructor
Do not call Function in Constructor.
*/
class ItemView3()
{
	super();

	//TODO:edit here

}
extends AView;


function ItemView3*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function ItemView3*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function ItemView3*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
