
/**
Constructor
Do not call Function in Constructor.
*/
class AutoSizeView()
{
	super();

	//TODO:edit here

}
extends AView;


function AutoSizeView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function AutoSizeView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function AutoSizeView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
