
/**
Constructor
Do not call Function in Constructor.
*/
class BadUsecaseView()
{
	super();

	//TODO:edit here

}
extends AView;


function BadUsecaseView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function BadUsecaseView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function BadUsecaseView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
