
/**
Constructor
Do not call Function in Constructor.
*/
class FlexLayoutView()
{
	super();

	//TODO:edit here

}
extends AView;


function FlexLayoutView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function FlexLayoutView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function FlexLayoutView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
