
/**
Constructor
Do not call Function in Constructor.
*/
class GridLayoutView2()
{
	super();

	//TODO:edit here

}
extends AView;


function GridLayoutView2*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function GridLayoutView2*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function GridLayoutView2*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
