
/**
Constructor
Do not call Function in Constructor.
*/
class GridLayoutView()
{
	super();

	//TODO:edit here

}
extends AView;


function GridLayoutView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function GridLayoutView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function GridLayoutView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
