
/**
Constructor
Do not call Function in Constructor.
*/
class LayoutView()
{
	super();

	//TODO:edit here

}
extends AView;


function LayoutView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function LayoutView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function LayoutView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
