
/**
Constructor
Do not call Function in Constructor.
*/
class TestView()
{
	super();

	//TODO:edit here

}
extends AView;


function TestView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function TestView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function TestView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
