
/**
Constructor
Do not call Function in Constructor.
*/
class Subview2()
{
	super();

	//TODO:edit here

}
extends AView;


function Subview2*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function Subview2*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function Subview2*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
