
/**
Constructor
Do not call Function in Constructor.
*/
class item2()
{
	super();

	//TODO:edit here

}
extends AView;


function item2*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function item2*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function item2*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};

function item2*onAView1Click(comp, info, e)
{

	AToast.show('Hello World!');

};

