
/**
Constructor
Do not call Function in Constructor.
*/
class subview1()
{
	super();

	//TODO:edit here

}
extends AView;


function subview1*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function subview1*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function subview1*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
